sonar.projectKey=thihapnaing_smartcart-web
sonar.organization=thihapnaing0310
sonar.projectName=smartcart-web

# Point to Angular source folder
sonar.sources=src

# Prevent SonarCloud from scanning heavy dependency folders or test files
sonar.exclusions=**/node_modules/**,**/*.spec.ts

sonar.sourceEncoding=UTF-8
